### ISSUE TITLE
Schema is no longer serializable

### ISSUE THREAD

**Issue by AnthonySteele** [7digital/SevenDigital.Api.Schema#1]
The .com website team have encountered an issue when upgrading to this library.

They expected the DTO objects to be marked as [Serializable] in a couple of places in their code. Since the schema is now a portable class lib it cannot use this attribute.

They do this in 2 places that I saw:

1)	In exceptions. I saw an exception that contains an artist DTO, and there are likely other exceptions containing other DTO types. The exception is expected to be serializable as per best practice. 

In this case I think it is acceptable for us to say [well don't do it](http://www.telegraph.co.uk/culture/comedy/10363116/Tommy-Cooper-25-great-jokes.html)  and advise that instead the id and name could be stored on the exception instead of the whole object.

2)	Cache. This is harder as caching of dtos is [pluggable in the wrapper](https://github.com/7digital/SevenDigital.Api.Wrapper/wiki/Response-caching). The [MemoryCache](http://msdn.microsoft.com/en-us/library/system.runtime.caching.memorycache(v=vs.110).aspx) does not require that objects stored in it be serializable (it doesn't need to serialise objects to store them in memory) but other caches such as Redis or MemCacheD will need to serialize objects somehow, and I do not know if they will require the serializable attribute.

I thought for a while that we could fix this by having Schema lib produce [a nuget package with multiple framework targets](http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package#Framework_Version_Folder_Structure)  e.g. portable and .net 3 and up, but there are complications as the api wrapper would depend on one or other of these binaries.

At present I don't see any comprehensive fix to this other than that the the .com site treat these DTOs as a reference, and use them by the "cut, paste and modify" import process.  A strength of the wrapper is that it will work with any appropriately annotated DTO type, so they can do this easily, just using the schema binary for [the required attributes](https://github.com/7digital/SevenDigital.Api.Schema/tree/master/src/Schema/Attributes).

As binary shared schema libs are widely regarded as being somewhere between "hard" and "too hard" this may be the way to do it for now.

Tangentially related:
-  The DTO schema is useful as a reference even if you aren't writing c# code. It can answer questions like "can there be multiple formats under a package?" (yes, there's a list)
-  Splitting the wrapper into engine and Schema is a very useful first step, but what we are seeing now is the difference  between schema and metadata attributes, both of which are in this library and it might be useful to split out.

**Comment by AnthonySteele** [comment]
I suggest that we pull back from a Portable class lib - there's no real need for this. 
Target a lowest common version of .Net, e.g, v3.5 so linq can be used if needed

**Comment by gregsochanik** [comment]
Agreed 100% :+1:, get rid of the PCL and reinstate Serializable. 

And 3.5 version of .NET is also fine by me. As far as I can see this would just be a minor version increment (1.2.1?)
